version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.1.2-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit
  test:
    docker:
      - image: circleci/php:8.1.2-fpm
        environment:
          APP_ENV: "testing"
          APP_KEY: "base64:your-base64-encoded-key"
          DB_CONNECTION: "mysql"
          DB_HOST: "127.0.0.1"
          DB_PORT: "3306"
          DB_DATABASE: "app_test"
          DB_USERNAME: "root"
          DB_PASSWORD: "password"
      - image: mysql:8.0.35
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: app_test
          MYSQL_USER: root